version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: dev
  reviewers:
  - the-code-monkey
  assignees:
  - the-code-monkey
