version: 2
registries:
  npm-registry-npm-pkg-github-com-aw-web-design:
    type: npm-registry
    url: https://npm.pkg.github.com/aw-web-design
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_AW_WEB_DESIGN_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: dev
  versioning-strategy: increase
  ignore:
  - dependency-name: style-dictionary
    versions:
    - 3.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.3.0
  - dependency-name: eslint-plugin-import
    versions:
    - 2.23.0
    - 2.23.1
  registries:
  - npm-registry-npm-pkg-github-com-aw-web-design
