version: 2.1
  
orbs:
  node: circleci/node@2.0.3
  
workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test

jobs:
  test:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: npm i makeshift && ./node_modules/.bin/makeshift -s @aw-web-design -r npm.pkg.github.com/:_authToken=$GITHUBTOKEN
      - run: ls -la
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: yarn
      - run: yarn lint
      - run: node generate.js
  deploy:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - attach_workspace:
          at: .
      - run: npm publish
