version: 2.1
  
orbs:
  node: circleci/node@2.0.3
  
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - /alpha-*/
                - /beta-*/
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - /alpha-*/
                - /beta-*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - /alpha-*/
                - /beta-*/

jobs:
  test:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: yarn
      - run: yarn lint
      - run: node generate.js
      - run: yarn release
  deploy:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - attach_workspace:
          at: .
      - run: yarn release
