version: 2.1
  
orbs:
  node: circleci/node@2.0.3
  
workflows:
  version: 2
  nextDeploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - /alpha-*/
                - /beta-*/
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - /alpha-*/
                - /beta-*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - /alpha-*/
                - /beta-*/

jobs:
  test:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: yarn lint
      - run: node src/generate.js
  nextDeploy:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Authenticate with registry
          command: npx npm-cli-login -u $USERNAME -p $PASSWORD -e $EMAIL -s @aw-web-design
      - run:
          name: Publish package
          command: yarn publish build --access=public --tag=next
  deploy:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Authenticate with registry
          command: npx npm-cli-login -u $USERNAME -p $PASSWORD -e $EMAIL -s @aw-web-design
      - run:
          name: Publish package
          command: yarn publish build --access=public
